### ISSUE TITLE
Failed to transform request with plugins: req_304fdb774c664e1992b877449d88076c

### ISSUE THREAD

**Issue by dscham** [dp-152/insomnia-plugins#8]
Hi there,

I love the idea of this plugin, especially because I have to send a lot of multiline strings. Which I didn't find an efficient way to convert for JSON yet. And writing my own tool is also kind of overkill, for my task at hand.

There is nothing secret in this, so I'm posting the YAML I entered here. Resulting in the error from the title, which is very useless and I couldn't find more detailed info. Maybe you have an idea why I get it.

```yaml
#instanceid 202172525
iamgeId: "4efbc0ba-2313-4fe1-842a-516f8652e729"

userData: |
  #cloud-config
  #hostname
  fqdn: dscntbvm2.dscntblan1

  #packages
  package_update: true
  package_upgrade: true
  package_reboot_if_required: true

  packages:
    - zsh
    - git

  #config
  disable_root: true
  locale: en_US
  timezone: Europe/Berlin

  #users
  user: 
    - name: root
      shell: /bin/zsh
  users:
    - default
    - name: dsc
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7GiAl8QFjKgRvcxe/stjrjW8cv3+14w5rnNPaAs7CLATadt1kEk0Kvo0GmNjTywxWznZJs0l81BL3YqkbVnaYe5sAXEljTM+ORYFDlFlcLb4gdBSTtIaMfo+CZ5TVkDoYPJwGqj2a52vSZRoowx7iWb14C5IyFlF4GmI4mRgyA9HqSr17vpf6mEUpUuO6cwQZI0vBRWcvLaXfesFITK1bZ8xDxSt+Juq39kjocMPIWO43Nk/fAbVJd0tg5hwSROxbEOrOE6/6YDA0l5ZomKoytb9+wJNU5Ba0c38u2LOK7CItv/LAH7V1Hqsb3Nq6BHl9v/o6q8N+pZXKYg0DkNScn1uzQbs/SQUwXzTwXaHG/Ai5bGxdjEMGPSj4cxoZIJbE7KGazUGRl7lTXwhCEkeuwRLxSX76axpsI5l561MQeERDOJiswhAZqfQEKQJMAYjeFMjDDYs+HcKxYXSEWxLkIPn21P9onhI9CQvGdwLefXNBsXK61BYbdXCoObHf3es= dscham@dsnb1
      sudo: ["ALL=(ALL) NOPASSWD:ALL"]
      lock_passwd: true
      shell: /bin/zsh
```
